# OCULAR Website - Netlify Configuration
#
# This file configures how the site is deployed on Netlify
# and handles routing/caching settings

# Build settings - Define where the site files are located
[build]
  publish = "/"  # Publishing from the root directory
  functions = "netlify/functions"  # Location of serverless functions

# Environment variables (DO NOT COMMIT THIS FILE WITH THE REAL TOKEN)
# Set these in the Netlify UI instead
[build.environment]
  # Token is redacted here - set in Netlify UI
  # FOURTHWALL_API_TOKEN = "ptkn_XXXX"

# Redirects for SPA and function paths
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Cache control for assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
