[build]
  publish = "."
  command = "# no build command"

[functions]
  directory = "api/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

# Handle asset paths
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/components/*"
  to = "/components/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/pages/:splat"
  status = 200
