[build]
  publish = "."
  command = "# no build command"

[functions]
  directory = "api/functions"

[[redirects]]
  from = "/api/user"
  to = "/.netlify/functions/auth/user"
  status = 200

[[redirects]]
  from = "/auth/login"
  to = "/.netlify/functions/auth/login"
  status = 200

[[redirects]]
  from = "/auth/logout"
  to = "/.netlify/functions/auth/logout"
  status = 200

[[redirects]]
  from = "/auth/discord/callback"
  to = "/.netlify/functions/auth/discord/callback"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/auth/discord/callback"
  status = 200

# Handle asset paths
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/components/*"
  to = "/components/:splat"
  status = 200

# Root path should serve index.html from pages directory
[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200

# Specific pages - try to match exact file first
[[redirects]]
  from = "/:page.html"
  to = "/pages/:page.html"
  status = 200

# SPA fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/pages/index.html"
  status = 200
